include: package:lints/recommended.yaml

linter:
  rules:
    no_duplicate_case_values: true
    no_self_assignments: true
    constant_identifier_names: false
    no_wildcard_variable_uses: true
    prefer_relative_imports: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    use_build_context_synchronously: false
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_specify_types: false
    avoid_double_and_int_checks: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_returning_null_for_void: true
    avoid_void_async: true
    await_only_futures: true
    cast_nullable_to_non_nullable: true
    curly_braces_in_flow_control_structures: true
    deprecated_consistency: true
    empty_catches: true
    empty_constructor_bodies: true
    file_names: true
    flutter_style_todos: true
    null_check_on_nullable_type_parameter: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_mixin: true
    prefer_spread_collections: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_colored_box: true
    use_decorated_box: true
    use_to_and_as_if_applicable: true
    sort_constructors_first: true