name: my_portfolio
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_riverpod: ^2.4.9
  intl: ^0.18.1
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.6
  responsive_framework: ^1.1.1
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  url_strategy: ^0.2.0
  font_awesome_flutter: ^10.6.0
  collection: ^1.18.0
  flutter_animate: ^4.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  scrollable_positioned_list: ^0.3.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  flutter_gen_runner: ^5.4.0 

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/skills/

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#0F172A"
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#0F172A"

  web: true

# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true

  image_path: "assets/images/logo.png"

  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"