name: my_portfolio
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_riverpod: ^2.6.1
  intl: ^0.18.1
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  url_strategy: ^0.3.0
  font_awesome_flutter: ^10.8.0
  collection: ^1.19.1
  flutter_animate: ^4.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  scrollable_positioned_list: ^0.3.8

  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  flutter_gen_runner: ^5.10.0 

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/skills/

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#0F172A"
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#0F172A"

  web: true

# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true

  image_path: "assets/images/logo.png"

  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"