// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnCVihiHxjIiXkTAF_e6vOi9TvzD7LdQ0',
    appId: '1:400554224855:web:bb7c6cff5f2d5d8d7f1492',
    messagingSenderId: '400554224855',
    projectId: 'mohamed-portfolio-a37de',
    authDomain: 'mohamed-portfolio-a37de.firebaseapp.com',
    storageBucket: 'mohamed-portfolio-a37de.firebasestorage.app',
    measurementId: 'G-XVGRCK2PYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPH5nLJeXI1VpkUy-3gTPwnKxuuXO5Og',
    appId: '1:400554224855:android:acf5e92a8a91418b7f1492',
    messagingSenderId: '400554224855',
    projectId: 'mohamed-portfolio-a37de',
    storageBucket: 'mohamed-portfolio-a37de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyErbfHP-QOB7PqJGQQdh10QkRxtQkl24',
    appId: '1:400554224855:ios:2bc29dd6e97334e87f1492',
    messagingSenderId: '400554224855',
    projectId: 'mohamed-portfolio-a37de',
    storageBucket: 'mohamed-portfolio-a37de.firebasestorage.app',
    iosBundleId: 'mohamedabdelbasit.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyErbfHP-QOB7PqJGQQdh10QkRxtQkl24',
    appId: '1:400554224855:ios:2bc29dd6e97334e87f1492',
    messagingSenderId: '400554224855',
    projectId: 'mohamed-portfolio-a37de',
    storageBucket: 'mohamed-portfolio-a37de.firebasestorage.app',
    iosBundleId: 'mohamedabdelbasit.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-92j7BewimtxwianD9h2wPGvOe5Y-t5o',
    appId: '1:400554224855:web:c032ad5a44d1884b7f1492',
    messagingSenderId: '400554224855',
    projectId: 'mohamed-portfolio-a37de',
    authDomain: 'mohamed-portfolio-a37de.firebaseapp.com',
    storageBucket: 'mohamed-portfolio-a37de.firebasestorage.app',
    measurementId: 'G-G2ZMX6FHQ7',
  );
}
