import 'constants.dart';

const myProjects = [
  {
    'title': 'Sura Mariam',
    'description':
        'Listen, Reeading and Save surat mariam offline and with smallest app size with very good sound and has many features like \n Qibla \n Azkar \n Notify With Zekr in time \n Questions And Tests',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.mariam',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/mariam/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/mariam/screenshot1.png',
      '$projectBaseURL/projects_images/mariam/screenshot2.png',
      '$projectBaseURL/projects_images/mariam/screenshot3.png',
      '$projectBaseURL/projects_images/mariam/screenshot4.png',
      '$projectBaseURL/projects_images/mariam/screenshot5.png',
      '$projectBaseURL/projects_images/mariam/screenshot6.png',
      '$projectBaseURL/projects_images/mariam/screenshot7.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Git',
      'GitHub',
      'RiverPod',
      'Restful API',
      'Responsive Design',
      'Local Notifications',
      'Hive',
      'Sound Playing',
    ],
  },
  {
    'title': 'Juz Tabarak',
    'description':
        'Listen, Reeading and Save Juz Tabarak offline and with smallest app size with very good sound and has many features like \n Qibla \n Azkar \n Notify With Zekr in time \n Questions And Tests',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.tabarak',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/tabarak/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/tabarak/screenshot1.png',
      '$projectBaseURL/projects_images/tabarak/screenshot2.png',
      '$projectBaseURL/projects_images/tabarak/screenshot3.png',
      '$projectBaseURL/projects_images/tabarak/screenshot4.png',
      '$projectBaseURL/projects_images/tabarak/screenshot5.png',
      '$projectBaseURL/projects_images/tabarak/screenshot6.png',
      '$projectBaseURL/projects_images/tabarak/screenshot7.png',
      '$projectBaseURL/projects_images/tabarak/screenshot8.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Git',
      'GitHub',
      'RiverPod',
      'Responsive Design',
      'Local Notifications',
      'Hive',
      'Sound Playing',
    ],
  },
  {
    'title': 'Hijri and Gregorian calendar',
    'description':
        '(+1M Downloads)\nThe Hijri and Gregorian calendar application displays:\nHijri calendar\nGregorian calendar\nConvert date from Hijri to Gregorian\nConverting the date from Gregorian to Hijri\nprayer time\nQiblah\nView public events\nView your special events\nView past and upcoming years and months\nnight mode\nArabic and English\nControl alerts',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.saudicalendars.calendar_app',
    'app_store': 'https://apps.apple.com/app/id1532182932',
    'web': null,
    'image': '$projectBaseURL/projects_images/hijri/logo.jpeg',
    'screenshots': [
      '$projectBaseURL/projects_images/hijri/screenshot1.png',
      '$projectBaseURL/projects_images/hijri/screenshot2.png',
      '$projectBaseURL/projects_images/hijri/screenshot3.png',
      '$projectBaseURL/projects_images/hijri/screenshot4.png',
      '$projectBaseURL/projects_images/hijri/screenshot5.png',
      '$projectBaseURL/projects_images/hijri/screenshot6.png',
      '$projectBaseURL/projects_images/hijri/screenshot7.png',
      '$projectBaseURL/projects_images/hijri/screenshot8.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Git',
      'GitHub',
      'RiverPod',
      'Restful API',
      'Responsive Design',
      'Local Notifications',
      'Hive',
    ],
  },
  {
    'title': 'Omni Lab',
    'description':
        'Omni labs is an application to help dentists to order dental lab services in easier and faster way , same time to follow the progress of their orders step by step',
    'google_play': null,
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Omni%20Labs/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot1.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot2.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot3.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot4.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot5.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot6.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'NodeJS',
      'mongoDB',
      'RestfulAPI',
      'Firebase',
      'SocketIO',
      'Responsive',
      'Express',
      'Git',
      'GitHub',
    ],
  },
  {
    'title': 'Saudi Calendar',
    'description':
        'A free Saudi calendar application to remind you of all occasions in Saudi Arabia using the Hijri and Gregorian date, for example:\n- Salary dates for employees and retirees.\n- Citizen account date.\n- Social security date.\n- School calendar.\n- Occasions Public.\n- Seminars and conferences.\n- Exhibitions and festivals.\n- Your special occasions. All events can be retrieved after deleting the application or syncing them with another device.\n- Today’s date.\n- Control all settings.\n- Dark mode .\nAnd other features in the application',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.saudicalendars.app',
    'app_store':
        'https://apps.apple.com/us/app/%D8%AA%D9%82%D9%88%D9%8A%D9%85-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9/id1479182106',
    'web': null,
    'image': '$projectBaseURL/projects_images/Saudi%20Calendars/icon.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot1.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot2.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot3.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot4.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot5.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot6.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot7.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot8.png'
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'Academic Calendar',
    'description':
        'Application of the academic calendar\naccording to the Ministry of Education in the Kingdom of Saudi Arabia\ncountdown to the date of vacations and tests\nwidgets to follow the nearest date directly\nfollow the salary date\nfollow public events\nadd a section for special events for the application user',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.saudicalendars.academic',
    'app_store':
        'https://apps.apple.com/us/app/%D8%A7%D9%84%D8%AA%D9%82%D9%88%D9%8A%D9%85-%D8%A7%D9%84%D8%AF%D8%B1%D8%A7%D8%B3%D9%8A-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A/id1319273089',
    'web': null,
    'image': '$projectBaseURL/projects_images/Academic%20Calendar/icon.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot1.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot2.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot3.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot4.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot5.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot6.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot7.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot8.png'
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'Prayer Times',
    'description':
        'Prayer times app is free and without ads.\nAlerts you to prayer times in all cities of the world.\nDisplay prayer times for the current day, upcoming days, and previous days.\nDirection of the qiblah.\nShow upcoming Islamic events.\nControl the alarm settings for each prayer.\nControl the choice of the muezzin, geographical location, and language.',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.prayer_times.app',
    'app_store': 'https://apps.apple.com/sa/app/prayer-times-app/id1557466684',
    'web': null,
    'image': '$projectBaseURL/projects_images/Prayer%20Times/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot1.jpeg',
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot2.jpeg',
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot3.jpeg',
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot4.jpeg',
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot5.jpeg'
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'Saudi Events',
    'description':
        'Saudi Events is concerned with displaying the latest events, festivals and events in Saudi Arabia with the possibility of saving, sharing and reminding them, for example:\n- Public events.\n- Seminars and conferences.\n- Exhibitions and festivals.\n- Seasons and events.\n- Appointment Salaries for employees and retirees.\n- Academic calendar.\n- Your special occasions. All occasions can be retrieved after deleting the application or syncing them with another device.\n- Today’s date.\n- Control of all settings.\n- Dark mode.\nAnd other Features in the application.',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.ksaevent.app',
    'app_store':
        'https://apps.apple.com/us/app/%D9%81%D8%B9%D8%A7%D9%84%D9%8A%D8%A7%D8%AA-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9/id6444774683',
    'web': null,
    'image': '$projectBaseURL/projects_images/KSA%20Events/logo.jpeg',
    'screenshots': [
      '$projectBaseURL/projects_images/KSA%20Events/screenshot1.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot2.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot3.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot4.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot5.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot6.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot7.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot8.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'Dleel Net',
    'description':
        'A guide to displaying the best applications, sites and social media accounts\nBuild your own favorites quickly\nAdd your favorite sites, applications and accounts\nA notebook to save your notes and tasks\nA blog to display new news and information\nAnd more..',
    'google_play':
        'https://play.google.com/store/apps/details?id=net.dleel.dleel',
    'app_store':
        'https://apps.apple.com/us/app/%D8%AF%D9%84%D9%8A%D9%84-%D9%86%D8%AA/id1588625301',
    'web': null,
    'image': '$projectBaseURL/projects_images/Dleel/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Dleel/screenshot1.png',
      '$projectBaseURL/projects_images/Dleel/screenshot2.png',
      '$projectBaseURL/projects_images/Dleel/screenshot3.png',
      '$projectBaseURL/projects_images/Dleel/screenshot4.png',
      '$projectBaseURL/projects_images/Dleel/screenshot5.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'Hayat Almuslim',
    'description':
        'For All Muslims This App Contains Quran, Hadith, Tafseer, Learning Quran, Azkar, Sebha And More Uploaded On Google Play',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.quran_and_azkar.quran_and_azkar_app',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Hayat%20Almuslim/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot1.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot2.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot3.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot4.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot5.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot6.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot7.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Hive',
      'GetX',
    ],
  },
  {
    'title': 'Bank El-Dam App',
    'description':
        'This App For Collect Blood From All Users To Hospitals And Others Need This Blood Uploaded On Google Play And App Store',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.bankeldam.egypt',
    'app_store':
        'https://apps.apple.com/eg/app/%D8%A8%D9%86%D9%83-%D8%A7%D9%84%D8%AF%D9%85/id1547670843?l=ar',
    'web': null,
    'image': '$projectBaseURL/projects_images/Bank%20Aldam/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Bank%20Aldam/screenshot1.png',
      '$projectBaseURL/projects_images/Bank%20Aldam/screenshot2.png',
      '$projectBaseURL/projects_images/Bank%20Aldam/screenshot3.png',
      '$projectBaseURL/projects_images/Bank%20Aldam/screenshot4.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Hive',
      'GetX',
    ],
  },
  {
    'title': 'Tejara E-Commerece',
    'description':
        'This App For E-Commerce Uploaded On Google Play And App Store',
    'google_play': null,
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Tejara/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Tejara/screenshot1.png',
      '$projectBaseURL/projects_images/Tejara/screenshot2.png',
      '$projectBaseURL/projects_images/Tejara/screenshot3.png',
      '$projectBaseURL/projects_images/Tejara/screenshot4.png',
      '$projectBaseURL/projects_images/Tejara/screenshot5.png',
      '$projectBaseURL/projects_images/Tejara/screenshot6.png',
      '$projectBaseURL/projects_images/Tejara/screenshot7.png',
      '$projectBaseURL/projects_images/Tejara/screenshot8.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Git',
      'GitHub',
      'Shared Preference',
      'Provider',
    ],
  },
  {
    'title': 'Wardi E-Commerece',
    'description':
        'This App For E-Commerce Uploaded On Google Play And App Store',
    'google_play': null,
    'app_store':
        'https://apps.apple.com/eg/app/%D9%85%D8%AA%D8%AC%D8%B1-%D9%88%D8%B1%D8%AF%D9%8A-wardi-store/id1560876131?l=ar',
    'web': null,
    'image': '$projectBaseURL/projects_images/Wardi/logo.webp',
    'screenshots': [
      '$projectBaseURL/projects_images/Wardi/screenshot1.webp',
      '$projectBaseURL/projects_images/Wardi/screenshot2.webp'
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Git',
      'GitHub',
      'Shared Preference',
      'Provider',
    ],
  },
  {
    'title': 'Afaky ERP',
    'description':
        'This App Is ERP System Mobile Version App And Also Work On Web , It Uploaded On Google Play And App Store',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.afakyerp.afaky',
    'app_store': 'https://apps.apple.com/us/app/afaky-app/id1622146478',
    'web': null,
    'image': '$projectBaseURL/projects_images/Afaky/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Afaky/screenshot1.png',
      '$projectBaseURL/projects_images/Afaky/screenshot2.png',
      '$projectBaseURL/projects_images/Afaky/screenshot3.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Shared Preferences',
      'Bloc',
    ],
  },
  {
    'title': 'Gala Order',
    'description':
        'This App For Food Ordering That You Can Order Food From Any Restaruant And Delivery Will Deliver It To You And It Has Delivery App And Two Control Panels For Admin And Restaurant And It Uploaded On Google Play And App Store',
    'google_play': null,
    'app_store': 'https://apps.apple.com/us/app/gala-order/id1640057386',
    'web': null,
    'image': '$projectBaseURL/projects_images/Gala%20Order/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Gala%20Order/screenshot1.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot2.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot3.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot4.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot5.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot6.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot7.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Shared Preferences',
      'GetX',
    ],
  },
  {
    'title': 'Gala Driver',
    'description': 'This App For The Delivery Of Gala Order App',
    'google_play': null,
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Gala%20Driver/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot1.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot2.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot3.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot4.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot5.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot6.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot7.jpeg',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Shared Preferences',
      'GetX',
    ],
  },
  {
    'title': 'QR Generator & Scanner',
    'description':
        'This App For Generate And Scan QR Code And Extrac All Data You Generated It Uploaded On Google Play',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.qrscannerandreader',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/QR%20Scanner/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/QR%20Scanner/screenshot1.png',
      '$projectBaseURL/projects_images/QR%20Scanner/screenshot2.png',
      '$projectBaseURL/projects_images/QR%20Scanner/screenshot3.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'QR Code',
      'Git',
      'GitHub',
      'Local Storage',
      'GetX',
    ],
  },
  {
    'title': 'Allemny Academy',
    'description':
        'This App Is Webview Based App For Allemny Academy Uploaded On Google Play',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.u3allemny.allemny',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Allemny/logo.jpeg',
    'screenshots': [
      '$projectBaseURL/projects_images/Allemny/screenshot1.png',
      '$projectBaseURL/projects_images/Allemny/screenshot2.png',
      '$projectBaseURL/projects_images/Allemny/screenshot3.png',
      '$projectBaseURL/projects_images/Allemny/screenshot4.png',
      '$projectBaseURL/projects_images/Allemny/screenshot5.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Webview',
      'Git',
      'GitHub',
      'GetX',
    ],
  },
  {
    'title': '2022 Stories',
    'description': 'Download All Text And Video Stories From One App',
    'google_play': null,
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Whatsapp%20Stories/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot1.png',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot2.jpeg',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot2.png',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot3.jpeg',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot4.jpeg',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot5.jpeg',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Local Storage',
      'Git',
      'GitHub',
      'GetX',
      'NodeJS',
      'Admin Dashboard',
      'Restful API'
    ],
  },
  {
    'title': 'Helpers',
    'description':
        'small social media network for sharing and posting and creating stories',
    'google_play': null,
    'app_store': 'https://apps.apple.com/us/app/helpers/id6444851510',
    'web': null,
    'image': '$projectBaseURL/projects_images/Helpers/logo.webp',
    'screenshots': [
      '$projectBaseURL/projects_images/Helpers/screenshot1.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot2.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot3.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot4.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot5.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot6.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot7.webp',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Local Storage',
      'Git',
      'GitHub',
      'GetX',
      'NodeJS',
      'Restful API'
    ],
  },
  {
    'title': 'Driving School Dashboard',
    'description':
        'Dashboard for controlling the driving school with all functionality needed for',
    'google_play': null,
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/blue_house_dashboard/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot1.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot2.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot3.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot4.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot5.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot6.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot7.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot8.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot9.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Flutter Web',
      'Git',
      'GitHub',
      'RiverPod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design'
    ],
  },
  {
    'title': 'Driving School Dashboard',
    'description':
        'Dashboard for controlling Driving school all operations and adding students delete and update and all financial operations',
    'google_play': null,
    'app_store': null,
    'web': null,
    'image':
        '$projectBaseURL/projects_images/driving_school_dashboard/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot1.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot2.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot3.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot4.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot5.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot6.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot7.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot8.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot9.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot10.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot11.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot12.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Flutter Web',
      'Git',
      'GitHub',
      'RiverPod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design'
    ],
  },
  {
    'title': 'Blue House - User',
    'description': 'Show and order gates from every where in qatar',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.pipeline.bluehousecustomerapp_v1',
    'app_store': 'https://apps.apple.com/us/app/blue-house-qatar/id6448504307',
    'web': null,
    'image': '$projectBaseURL/projects_images/Blue%20House%20-%20User/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot1.png',
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot2.png',
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot3.png',
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot4.png',
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot5.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Git',
      'GitHub',
      'RiverPod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design'
    ],
  },
];
