// GENERATED content — the studio's project catalogue.
// Images are bundled under assets/projects/<slug>/.
import 'models/project.dart';

const List<Project> projects = [
  Project(
    slug: 'vibezo',
    title: 'ViBE ZO',
    kind: ProjectKind.platform,
    featured: true,
    category: 'Social Livestreaming',
    tagline: 'A social livestreaming & short-video platform',
    year: '2026',
    role: 'Product architecture · Flutter app · NestJS backend',
    description:
        'A full-stack social livestreaming and short-video platform — live PK battles, real-time gifting, a dual-wallet creator economy and a NestJS backend engineered for high concurrency.',
    longDescription:
        'ViBE ZO is our flagship build: a creator-economy platform that blends Bigo-style live streaming with a TikTok-style short-video feed. The Flutter client drives multi-guest live rooms, PK battles, beauty/AR filters and animated real-time gifting, while a NestJS + PostgreSQL backend orchestrates streaming providers, a dual-wallet ledger, async vibe rendering and Socket.IO real-time events. It ships in 9 languages with Shorebird over-the-air updates.',
    platforms: [
      'iOS',
      'Android',
    ],
    googlePlay: 'https://play.google.com/store/apps/details?id=vibe.zo.app',
    appStore: 'https://apps.apple.com/us/app/vibe-zo/id6756111783',
    image: 'assets/projects/vibezo/logo.png',
    screenshots: [
      'assets/projects/vibezo/screenshot1.jpeg',
      'assets/projects/vibezo/screenshot2.jpeg',
      'assets/projects/vibezo/screenshot3.jpeg',
      'assets/projects/vibezo/screenshot4.jpeg',
      'assets/projects/vibezo/screenshot5.jpeg',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'go_router',
      'Socket.IO',
      'ZegoCloud',
      'Stripe',
      'Firebase',
      'Dio',
      'Hive',
      'Lottie',
    ],
    features: [
      'Live streaming — solo, up to 3 guest co-hosts and host-vs-host PK battles (ZegoCloud)',
      'Real-time animated gifting with a parallel + sequential rendering pipeline',
      'Short-form vertical "Vibes" feed with a server-side rendering queue',
      'Dual-wallet economy — recharge via Stripe & in-app purchase, creator cash-out',
      'Beauty & AR filters, makeup presets and color filters',
      'Agencies, fan groups, a 300-level XP system and global leaderboards',
      '1:1 and group chat with audio, media and reactions over Socket.IO',
      'Multi-provider auth: phone/OTP, email, Google & Apple',
    ],
    backendStack: [
      'NestJS',
      'TypeScript',
      'PostgreSQL',
      'Prisma',
      'Redis',
      'BullMQ',
      'Socket.IO',
      'Cloudflare R2',
      'Stripe',
      'Firebase Admin',
      'Turborepo',
    ],
  ),
  Project(
    slug: 'crystal_crush',
    title: 'Crystal Crush',
    kind: ProjectKind.game,
    category: 'Match-3 Game',
    tagline: 'A match-3 puzzle with 1000 levels',
    year: '2026',
    description:
        'A polished match-3 puzzle game — 1000 hand-tuned levels, cascading combos, special gems, boosters, a lives system and daily rewards.',
    longDescription:
        'Crystal Crush is a production match-3 game with a 1000-level Candy-Crush-style map. It features smart match detection, cascading chain reactions with combo multipliers, special gems and blockers, a coins/gems economy, a lives system and 30-day daily-reward streaks — all wrapped in a full audio system and AdMob monetization.',
    platforms: [
      'iOS',
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.crystalcrush',
    appStore: 'https://apps.apple.com/us/app/crystal-crush/id6755475781',
    image: 'assets/projects/crystal_crush/logo.png',
    screenshots: [
      'assets/projects/crystal_crush/screenshot1.png',
      'assets/projects/crystal_crush/screenshot2.png',
      'assets/projects/crystal_crush/screenshot3.png',
      'assets/projects/crystal_crush/screenshot4.png',
      'assets/projects/crystal_crush/screenshot5.png',
      'assets/projects/crystal_crush/screenshot6.png',
      'assets/projects/crystal_crush/screenshot7.png',
      'assets/projects/crystal_crush/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'Hive',
      'Google Mobile Ads',
      'Firebase',
      'Responsive',
    ],
    features: [
      '1000 progressive levels on a vertical world map',
      'Cascading chain reactions and combo multipliers',
      'Special gems — striped, wrapped and color bombs',
      'Boosters, lives, coins/gems and 30-day daily rewards',
      'Full music & SFX system with AdMob monetization',
    ],
  ),
  Project(
    slug: 'smart_spend',
    title: 'Smart Spend',
    kind: ProjectKind.mobile,
    category: 'Finance',
    tagline: 'Personal finance, synced everywhere',
    year: '2025',
    description:
        'A personal-finance app for tracking expenses, invoices and budgets, with interactive analytics and real-time multi-device sync.',
    longDescription:
        'Smart Spend helps people stay on top of their money: track expenses, manage recurring invoices, set category budgets and read it all back through interactive charts. It is offline-first with Firestore cloud sync, supports Google/Apple sign-in and a guest mode, and ships in English and Arabic.',
    platforms: [
      'iOS',
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.smart_spend',
    appStore: 'https://apps.apple.com/eg/app/smart-spend/id6744930597',
    image: 'assets/projects/smart_spend/logo.png',
    screenshots: [
      'assets/projects/smart_spend/screenshot1.png',
      'assets/projects/smart_spend/screenshot2.png',
      'assets/projects/smart_spend/screenshot3.png',
      'assets/projects/smart_spend/screenshot4.png',
      'assets/projects/smart_spend/screenshot5.png',
      'assets/projects/smart_spend/screenshot6.png',
      'assets/projects/smart_spend/screenshot7.png',
      'assets/projects/smart_spend/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'Firebase',
      'Cloud Firestore',
      'Hive',
      'fl_chart',
      'Easy Localization',
    ],
    features: [
      'Expense, invoice and budget tracking with custom categories',
      'Interactive charts and monthly / yearly reports',
      'Offline-first with real-time Firestore cloud sync',
      'Google & Apple sign-in, plus a local guest mode',
      'Reminders, multi-currency and English / Arabic',
    ],
  ),
  Project(
    slug: 'taskaty',
    title: 'Taskaty',
    kind: ProjectKind.mobile,
    category: 'Productivity',
    tagline: 'Tasks, subtasks & smart reminders',
    year: '2025',
    description:
        'A task manager with subtasks, priorities, recurring reminders and real-time cloud sync across devices.',
    longDescription:
        'Taskaty organizes work into ongoing, completed and recurring views. Tasks break down into subtasks with visual progress, carry priorities and color categories, and fire daily/weekly/monthly or custom notifications. It syncs through Firestore with offline Hive storage.',
    platforms: [
      'iOS',
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.taskaty',
    appStore: 'https://apps.apple.com/us/app/id6740486266',
    image: 'assets/projects/taskaty/logo.png',
    screenshots: [
      'assets/projects/taskaty/screenshot1.png',
      'assets/projects/taskaty/screenshot2.png',
      'assets/projects/taskaty/screenshot3.png',
      'assets/projects/taskaty/screenshot4.png',
      'assets/projects/taskaty/screenshot5.png',
      'assets/projects/taskaty/screenshot6.png',
      'assets/projects/taskaty/screenshot7.png',
      'assets/projects/taskaty/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'Firebase',
      'Cloud Firestore',
      'Local Notifications',
      'Easy Localization',
    ],
    features: [
      'Tasks with subtasks and visual progress bars',
      'Ongoing / completed / recurring organization',
      'Priorities, color categories and combined filters',
      'Daily, weekly, monthly or custom notifications',
      'Firestore sync with offline Hive storage',
    ],
  ),
  Project(
    slug: 'brain_land',
    title: 'Brain Land',
    kind: ProjectKind.game,
    category: 'Kids · Educational',
    tagline: 'A learning adventure for kids 5–11',
    year: '2026',
    description:
        'An educational adventure game for children — four themed zones teach math, logic, memory and shapes through playful mini-games.',
    longDescription:
        'Brain Land turns early learning into an adventure across four worlds — Math Forest, Logic Mountain, Memory River and Shape Valley. Difficulty adapts as kids progress, with stars, reward chests, avatar customization and daily streaks, all in a kid-safe interface.',
    platforms: [
      'iOS',
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.brainland',
    appStore: 'https://apps.apple.com/us/app/brain-land-game/id6755624622',
    image: 'assets/projects/brain_land/logo.png',
    screenshots: [
      'assets/projects/brain_land/screenshot1.png',
      'assets/projects/brain_land/screenshot2.png',
      'assets/projects/brain_land/screenshot3.png',
      'assets/projects/brain_land/screenshot4.png',
      'assets/projects/brain_land/screenshot5.png',
      'assets/projects/brain_land/screenshot6.png',
      'assets/projects/brain_land/screenshot7.png',
      'assets/projects/brain_land/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'Hive',
      'Google Mobile Ads',
      'Firebase',
    ],
    features: [
      'Four zones: Math Forest, Logic Mountain, Memory River, Shape Valley',
      'Adaptive difficulty with stars and reward chests',
      'Avatar customization, pets and daily login rewards',
      'Kid-safe design with Firebase analytics',
    ],
  ),
  Project(
    slug: 'boardverse',
    title: 'BoardVerse',
    kind: ProjectKind.platform,
    category: 'Multiplayer Games',
    tagline: 'Five classic games, one platform',
    year: '2026',
    description:
        'A real-time multiplayer board-game platform — UNO, Domino, Chess Blitz, XO and Connect Four with unified profiles, matchmaking, leaderboards and tournaments.',
    longDescription:
        'BoardVerse unifies five classic games under one account, real-time engine and progression system. Players matchmake into public or private rooms, climb global and per-game leaderboards, enter cross-game tournaments and chat with emotes — all powered by Firebase real-time infrastructure. (Shown here with concept & onboarding art.)',
    platforms: [
      'iOS',
      'Android',
    ],
    image: 'assets/projects/boardverse/logo.png',
    screenshots: [
      'assets/projects/boardverse/screenshot1.png',
      'assets/projects/boardverse/screenshot2.png',
      'assets/projects/boardverse/screenshot3.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'Firebase',
      'Cloud Firestore',
      'Cloud Functions',
      'chess.dart',
      'Easy Localization',
    ],
    features: [
      'Five games: UNO, Domino, Chess Blitz, XO and Connect Four',
      'Real-time multiplayer with public/private room matchmaking',
      'Unified profile, friends, chat and emotes',
      'Global, per-game and friends leaderboards',
      'Cross-game tournaments and achievements',
    ],
    backendStack: [
      'Firebase',
      'Cloud Firestore',
      'Cloud Functions',
      'Firebase Auth',
    ],
  ),
  Project(
    slug: 'hijri',
    title: 'Hijri & Gregorian Calendar',
    kind: ProjectKind.mobile,
    category: 'Calendar · 1M+ downloads',
    tagline: 'Hijri/Gregorian calendar with 1M+ downloads',
    year: '2020',
    description:
        '(+1M downloads) A dual Hijri/Gregorian calendar with date conversion, prayer times, qibla, public & personal events, and synced backups.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.saudicalendars.calendar_app',
    appStore: 'https://apps.apple.com/app/id1532182932',
    image: 'assets/projects/hijri/logo.jpeg',
    screenshots: [
      'assets/projects/hijri/screenshot1.png',
      'assets/projects/hijri/screenshot2.png',
      'assets/projects/hijri/screenshot3.png',
      'assets/projects/hijri/screenshot4.jpeg',
      'assets/projects/hijri/screenshot5.jpeg',
      'assets/projects/hijri/screenshot6.jpeg',
      'assets/projects/hijri/screenshot7.jpeg',
      'assets/projects/hijri/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'Restful API',
      'Firebase',
      'Local Notifications',
      'Hive',
    ],
  ),
  Project(
    slug: 'afaky',
    title: 'Afaky ERP',
    kind: ProjectKind.mobile,
    category: 'ERP',
    tagline: 'Mobile + web client for an ERP system',
    year: '2022',
    description:
        'The mobile and web client for the Afaky ERP system, covering core business operations on the go.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.afakyerp.afaky',
    appStore: 'https://apps.apple.com/us/app/afaky-app/id1622146478',
    image: 'assets/projects/afaky/logo.png',
    screenshots: [
      'assets/projects/afaky/screenshot1.png',
      'assets/projects/afaky/screenshot2.png',
      'assets/projects/afaky/screenshot3.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'Bloc',
      'Shared Preferences',
    ],
  ),
  Project(
    slug: 'gala_order',
    title: 'Gala Order',
    kind: ProjectKind.platform,
    category: 'Food Delivery',
    tagline: 'A full food-ordering & delivery system',
    year: '2022',
    description:
        'A food-ordering platform — order from any restaurant with delivery, paired with a driver app and admin/restaurant control panels.',
    platforms: [
      'iOS',
      'Android',
    ],
    appStore: 'https://apps.apple.com/us/app/gala-order/id1640057386',
    image: 'assets/projects/gala_order/logo.png',
    screenshots: [
      'assets/projects/gala_order/screenshot1.png',
      'assets/projects/gala_order/screenshot2.png',
      'assets/projects/gala_order/screenshot3.png',
      'assets/projects/gala_order/screenshot4.png',
      'assets/projects/gala_order/screenshot5.png',
      'assets/projects/gala_order/screenshot6.png',
      'assets/projects/gala_order/screenshot7.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'GetX',
      'Shared Preferences',
    ],
  ),
  Project(
    slug: 'blue_house_user',
    title: 'Blue House',
    kind: ProjectKind.mobile,
    category: 'Marketplace · Qatar',
    tagline: 'Order gates across Qatar',
    year: '2023',
    description:
        'Browse and order gates from anywhere in Qatar, backed by a Node.js + MongoDB API.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.pipeline.bluehousecustomerapp_v1',
    appStore: 'https://apps.apple.com/us/app/blue-house-qatar/id6448504307',
    image: 'assets/projects/blue_house_user/logo.png',
    screenshots: [
      'assets/projects/blue_house_user/screenshot1.png',
      'assets/projects/blue_house_user/screenshot2.png',
      'assets/projects/blue_house_user/screenshot3.png',
      'assets/projects/blue_house_user/screenshot4.png',
      'assets/projects/blue_house_user/screenshot5.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design',
    ],
  ),
  Project(
    slug: 'omni_labs',
    title: 'Omni Lab',
    kind: ProjectKind.platform,
    category: 'Dental B2B',
    tagline: 'Dental lab ordering & tracking',
    year: '2021',
    description:
        'Helps dentists order dental-lab services faster and track each order\'s progress step by step — a full-stack build with a Node.js/MongoDB backend and Socket.IO.',
    platforms: [
      'iOS',
      'Android',
    ],
    image: 'assets/projects/omni_labs/logo.png',
    screenshots: [
      'assets/projects/omni_labs/screenshot1.png',
      'assets/projects/omni_labs/screenshot2.png',
      'assets/projects/omni_labs/screenshot3.png',
      'assets/projects/omni_labs/screenshot4.png',
      'assets/projects/omni_labs/screenshot5.png',
      'assets/projects/omni_labs/screenshot6.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'NodeJS',
      'Express',
      'mongoDB',
      'Socket.IO',
      'Firebase',
      'Restful API',
    ],
    backendStack: [
      'Node.js',
      'Express',
      'MongoDB',
      'Socket.IO',
    ],
  ),
  Project(
    slug: 'driving_school_dashboard',
    title: 'Driving School Dashboard',
    kind: ProjectKind.web,
    category: 'Web Dashboard',
    tagline: 'Operations dashboard for a driving school',
    year: '2023',
    description:
        'A Flutter Web dashboard to run a driving school end to end — students, scheduling and all financial operations — over a Node.js/MongoDB API.',
    platforms: [
      'Web',
    ],
    image: 'assets/projects/driving_school_dashboard/logo.png',
    screenshots: [
      'assets/projects/driving_school_dashboard/screenshot1.png',
      'assets/projects/driving_school_dashboard/screenshot2.png',
      'assets/projects/driving_school_dashboard/screenshot3.png',
      'assets/projects/driving_school_dashboard/screenshot4.png',
      'assets/projects/driving_school_dashboard/screenshot5.png',
      'assets/projects/driving_school_dashboard/screenshot6.png',
      'assets/projects/driving_school_dashboard/screenshot7.png',
      'assets/projects/driving_school_dashboard/screenshot8.png',
      'assets/projects/driving_school_dashboard/screenshot9.png',
      'assets/projects/driving_school_dashboard/screenshot10.png',
      'assets/projects/driving_school_dashboard/screenshot11.png',
      'assets/projects/driving_school_dashboard/screenshot12.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Flutter Web',
      'Riverpod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design',
    ],
    backendStack: [
      'Node.js',
      'Express',
      'MongoDB',
    ],
  ),
  Project(
    slug: 'blue_house_dashboard',
    title: 'Blue House Dashboard',
    kind: ProjectKind.web,
    category: 'Web Dashboard',
    tagline: 'Admin dashboard for the Blue House platform',
    year: '2023',
    description:
        'The Flutter Web admin dashboard powering the Blue House marketplace — catalog, orders and operations management.',
    platforms: [
      'Web',
    ],
    image: 'assets/projects/blue_house_dashboard/logo.png',
    screenshots: [
      'assets/projects/blue_house_dashboard/screenshot1.png',
      'assets/projects/blue_house_dashboard/screenshot2.png',
      'assets/projects/blue_house_dashboard/screenshot3.png',
      'assets/projects/blue_house_dashboard/screenshot4.png',
      'assets/projects/blue_house_dashboard/screenshot5.png',
      'assets/projects/blue_house_dashboard/screenshot6.png',
      'assets/projects/blue_house_dashboard/screenshot7.png',
      'assets/projects/blue_house_dashboard/screenshot8.png',
      'assets/projects/blue_house_dashboard/screenshot9.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Flutter Web',
      'Riverpod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design',
    ],
    backendStack: [
      'Node.js',
      'Express',
      'MongoDB',
    ],
  ),
  Project(
    slug: 'helpers',
    title: 'Helpers',
    kind: ProjectKind.platform,
    category: 'Social Network',
    tagline: 'A small social network',
    year: '2022',
    description:
        'A compact social network for posting, sharing and creating stories, backed by a Node.js API.',
    platforms: [
      'iOS',
    ],
    appStore: 'https://apps.apple.com/us/app/helpers/id6444851510',
    image: 'assets/projects/helpers/logo.webp',
    screenshots: [
      'assets/projects/helpers/screenshot1.webp',
      'assets/projects/helpers/screenshot2.webp',
      'assets/projects/helpers/screenshot3.webp',
      'assets/projects/helpers/screenshot4.webp',
      'assets/projects/helpers/screenshot5.webp',
      'assets/projects/helpers/screenshot6.webp',
      'assets/projects/helpers/screenshot7.webp',
    ],
    skills: [
      'Flutter',
      'Dart',
      'NodeJS',
      'Restful API',
      'GetX',
      'Local Storage',
    ],
    backendStack: [
      'Node.js',
      'Restful API',
    ],
  ),
  Project(
    slug: 'saudi_calendars',
    title: 'Saudi Calendar',
    kind: ProjectKind.mobile,
    category: 'Calendar',
    tagline: 'Saudi occasions on Hijri & Gregorian dates',
    year: '2020',
    description:
        'A free Saudi calendar that surfaces salary dates, citizen-account and social-security dates, school terms and public occasions, with home-screen widgets and dark mode.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.saudicalendars.app',
    appStore: 'https://apps.apple.com/us/app/id1479182106',
    image: 'assets/projects/saudi_calendars/icon.png',
    screenshots: [
      'assets/projects/saudi_calendars/screenshot1.png',
      'assets/projects/saudi_calendars/screenshot2.png',
      'assets/projects/saudi_calendars/screenshot3.png',
      'assets/projects/saudi_calendars/screenshot4.png',
      'assets/projects/saudi_calendars/screenshot5.png',
      'assets/projects/saudi_calendars/screenshot6.png',
      'assets/projects/saudi_calendars/screenshot7.png',
      'assets/projects/saudi_calendars/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'Home Widget',
      'Hive',
      'Riverpod',
    ],
  ),
  Project(
    slug: 'ksa_events',
    title: 'Saudi Events',
    kind: ProjectKind.mobile,
    category: 'Events',
    tagline: 'Latest events & festivals in Saudi Arabia',
    year: '2021',
    description:
        'Discover the latest events, festivals and seasons across Saudi Arabia, with saving, sharing, reminders and synced personal occasions.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.ksaevent.app',
    appStore: 'https://apps.apple.com/us/app/id6444774683',
    image: 'assets/projects/ksa_events/logo.jpeg',
    screenshots: [
      'assets/projects/ksa_events/screenshot1.png',
      'assets/projects/ksa_events/screenshot2.png',
      'assets/projects/ksa_events/screenshot3.png',
      'assets/projects/ksa_events/screenshot4.png',
      'assets/projects/ksa_events/screenshot5.png',
      'assets/projects/ksa_events/screenshot6.png',
      'assets/projects/ksa_events/screenshot7.png',
      'assets/projects/ksa_events/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'Home Widget',
      'Hive',
      'Riverpod',
    ],
  ),
  Project(
    slug: 'prayer_times',
    title: 'Prayer Times',
    kind: ProjectKind.mobile,
    category: 'Islamic',
    tagline: 'Worldwide prayer times, ad-free',
    year: '2021',
    description:
        'Free, ad-free prayer times for every city in the world — qibla direction, upcoming Islamic events and per-prayer alarm controls.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.prayer_times.app',
    appStore: 'https://apps.apple.com/sa/app/prayer-times-app/id1557466684',
    image: 'assets/projects/prayer_times/logo.png',
    screenshots: [
      'assets/projects/prayer_times/screenshot1.jpeg',
      'assets/projects/prayer_times/screenshot2.jpeg',
      'assets/projects/prayer_times/screenshot3.jpeg',
      'assets/projects/prayer_times/screenshot4.jpeg',
      'assets/projects/prayer_times/screenshot5.jpeg',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'Home Widget',
      'Hive',
      'Riverpod',
    ],
  ),
  Project(
    slug: 'academic_calendar',
    title: 'Academic Calendar',
    kind: ProjectKind.mobile,
    category: 'Calendar',
    tagline: 'Saudi academic calendar with countdowns',
    year: '2020',
    description:
        'The Saudi Ministry of Education academic calendar with countdowns to holidays and exams, home-screen widgets, salary and public-event tracking.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.saudicalendars.academic',
    appStore: 'https://apps.apple.com/us/app/id1319273089',
    image: 'assets/projects/academic_calendar/icon.png',
    screenshots: [
      'assets/projects/academic_calendar/screenshot1.png',
      'assets/projects/academic_calendar/screenshot2.png',
      'assets/projects/academic_calendar/screenshot3.png',
      'assets/projects/academic_calendar/screenshot4.png',
      'assets/projects/academic_calendar/screenshot5.png',
      'assets/projects/academic_calendar/screenshot6.png',
      'assets/projects/academic_calendar/screenshot7.png',
      'assets/projects/academic_calendar/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'Home Widget',
      'Hive',
      'Riverpod',
    ],
  ),
  Project(
    slug: 'dleel',
    title: 'Dleel Net',
    kind: ProjectKind.mobile,
    category: 'Directory',
    tagline: 'A guide to the best apps, sites & accounts',
    year: '2021',
    description:
        'A directory of the best apps, sites and social accounts — build favorites, keep notes and tasks, and follow a built-in blog.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay: 'https://play.google.com/store/apps/details?id=net.dleel.dleel',
    appStore: 'https://apps.apple.com/us/app/id1588625301',
    image: 'assets/projects/dleel/logo.png',
    screenshots: [
      'assets/projects/dleel/screenshot1.png',
      'assets/projects/dleel/screenshot2.png',
      'assets/projects/dleel/screenshot3.png',
      'assets/projects/dleel/screenshot4.png',
      'assets/projects/dleel/screenshot5.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'Hive',
      'Riverpod',
    ],
  ),
  Project(
    slug: 'hayat_almuslim',
    title: 'Hayat Almuslim',
    kind: ProjectKind.mobile,
    category: 'Islamic',
    tagline: 'Quran, Hadith, Tafseer & Azkar',
    year: '2021',
    description:
        'An all-in-one Islamic companion: Quran, Hadith, Tafseer, Quran learning, Azkar and a Sebha.',
    platforms: [
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.quran_and_azkar.quran_and_azkar_app',
    image: 'assets/projects/hayat_almuslim/logo.png',
    screenshots: [
      'assets/projects/hayat_almuslim/screenshot1.png',
      'assets/projects/hayat_almuslim/screenshot2.png',
      'assets/projects/hayat_almuslim/screenshot3.png',
      'assets/projects/hayat_almuslim/screenshot4.png',
      'assets/projects/hayat_almuslim/screenshot5.png',
      'assets/projects/hayat_almuslim/screenshot6.png',
      'assets/projects/hayat_almuslim/screenshot7.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'Hive',
      'GetX',
    ],
  ),
  Project(
    slug: 'bank_aldam',
    title: 'Bank El-Dam',
    kind: ProjectKind.mobile,
    category: 'Healthcare',
    tagline: 'Connecting blood donors with hospitals',
    year: '2020',
    description:
        'Connects blood donors with hospitals and people in need of blood donations.',
    platforms: [
      'Android',
      'iOS',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.bankeldam.egypt',
    appStore: 'https://apps.apple.com/eg/app/id1547670843',
    image: 'assets/projects/bank_aldam/logo.png',
    screenshots: [
      'assets/projects/bank_aldam/screenshot1.png',
      'assets/projects/bank_aldam/screenshot2.png',
      'assets/projects/bank_aldam/screenshot3.png',
      'assets/projects/bank_aldam/screenshot4.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'Hive',
      'GetX',
    ],
  ),
  Project(
    slug: 'mariam',
    title: 'Sura Mariam',
    kind: ProjectKind.mobile,
    category: 'Quran',
    tagline: 'Listen, read & save Surat Mariam offline',
    year: '2019',
    description:
        'Listen to, read and save Surat Mariam offline in a tiny app — with qibla, azkar, timed reminders and quizzes.',
    platforms: [
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.mariam',
    image: 'assets/projects/mariam/logo.png',
    screenshots: [
      'assets/projects/mariam/screenshot1.jpg',
      'assets/projects/mariam/screenshot2.jpg',
      'assets/projects/mariam/screenshot3.jpg',
      'assets/projects/mariam/screenshot4.jpg',
      'assets/projects/mariam/screenshot5.jpg',
      'assets/projects/mariam/screenshot6.jpg',
      'assets/projects/mariam/screenshot7.jpg',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'Restful API',
      'Local Notifications',
      'Hive',
      'Sound Playing',
    ],
  ),
  Project(
    slug: 'tabarak',
    title: 'Juz Tabarak',
    kind: ProjectKind.mobile,
    category: 'Quran',
    tagline: 'Listen, read & save Juz Tabarak offline',
    year: '2019',
    description:
        'Listen to, read and save Juz Tabarak offline in a tiny app — with qibla, azkar, timed reminders and quizzes.',
    platforms: [
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.tabarak',
    image: 'assets/projects/tabarak/logo.png',
    screenshots: [
      'assets/projects/tabarak/screenshot1.jpg',
      'assets/projects/tabarak/screenshot2.jpg',
      'assets/projects/tabarak/screenshot3.jpg',
      'assets/projects/tabarak/screenshot4.jpg',
      'assets/projects/tabarak/screenshot5.jpg',
      'assets/projects/tabarak/screenshot6.jpg',
      'assets/projects/tabarak/screenshot7.jpg',
      'assets/projects/tabarak/screenshot8.jpg',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Riverpod',
      'Local Notifications',
      'Hive',
      'Sound Playing',
    ],
  ),
  Project(
    slug: 'gala_driver',
    title: 'Gala Driver',
    kind: ProjectKind.mobile,
    category: 'Delivery',
    tagline: 'The delivery app for Gala Order',
    year: '2022',
    description:
        'The driver companion app for the Gala Order food-delivery platform.',
    platforms: [
      'Android',
      'iOS',
    ],
    image: 'assets/projects/gala_driver/logo.png',
    screenshots: [
      'assets/projects/gala_driver/screenshot1.jpeg',
      'assets/projects/gala_driver/screenshot2.jpeg',
      'assets/projects/gala_driver/screenshot3.jpeg',
      'assets/projects/gala_driver/screenshot4.jpeg',
      'assets/projects/gala_driver/screenshot5.jpeg',
      'assets/projects/gala_driver/screenshot6.jpeg',
      'assets/projects/gala_driver/screenshot7.jpeg',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Firebase',
      'GetX',
      'Shared Preferences',
    ],
  ),
  Project(
    slug: 'qr_scanner',
    title: 'QR Generator & Scanner',
    kind: ProjectKind.mobile,
    category: 'Utility',
    tagline: 'Generate & scan QR codes',
    year: '2021',
    description:
        'Generate and scan QR codes and extract all the data you\'ve created, stored locally.',
    platforms: [
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.qrscannerandreader',
    image: 'assets/projects/qr_scanner/logo.png',
    screenshots: [
      'assets/projects/qr_scanner/screenshot1.png',
      'assets/projects/qr_scanner/screenshot2.png',
      'assets/projects/qr_scanner/screenshot3.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'QR Code',
      'GetX',
      'Local Storage',
    ],
  ),
  Project(
    slug: 'allemny',
    title: 'Allemny Academy',
    kind: ProjectKind.mobile,
    category: 'Education',
    tagline: 'A WebView app for Allemny Academy',
    year: '2021',
    description: 'A WebView-based companion app for Allemny Academy.',
    platforms: [
      'Android',
    ],
    googlePlay:
        'https://play.google.com/store/apps/details?id=com.u3allemny.allemny',
    image: 'assets/projects/allemny/logo.jpeg',
    screenshots: [
      'assets/projects/allemny/screenshot1.png',
      'assets/projects/allemny/screenshot2.png',
      'assets/projects/allemny/screenshot3.png',
      'assets/projects/allemny/screenshot4.png',
      'assets/projects/allemny/screenshot5.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Webview',
      'GetX',
    ],
  ),
  Project(
    slug: 'whatsapp_stories',
    title: '2022 Stories',
    kind: ProjectKind.mobile,
    category: 'Utility',
    tagline: 'Save text & video stories',
    year: '2021',
    description:
        'Download text and video stories from a single app, served by a Node.js backend and admin dashboard.',
    platforms: [
      'Android',
    ],
    image: 'assets/projects/whatsapp_stories/logo.png',
    screenshots: [
      'assets/projects/whatsapp_stories/screenshot1.png',
      'assets/projects/whatsapp_stories/screenshot2.jpeg',
      'assets/projects/whatsapp_stories/screenshot2.png',
      'assets/projects/whatsapp_stories/screenshot3.jpeg',
      'assets/projects/whatsapp_stories/screenshot4.jpeg',
      'assets/projects/whatsapp_stories/screenshot5.jpeg',
    ],
    skills: [
      'Flutter',
      'Dart',
      'NodeJS',
      'Restful API',
      'Admin Dashboard',
      'GetX',
      'Local Storage',
    ],
    backendStack: [
      'Node.js',
      'Restful API',
    ],
  ),
  Project(
    slug: 'tejara',
    title: 'Tejara',
    kind: ProjectKind.mobile,
    category: 'E-Commerce',
    tagline: 'An e-commerce mobile app',
    year: '2020',
    description: 'An e-commerce shopping app.',
    platforms: [
      'Android',
      'iOS',
    ],
    image: 'assets/projects/tejara/logo.png',
    screenshots: [
      'assets/projects/tejara/screenshot1.png',
      'assets/projects/tejara/screenshot2.png',
      'assets/projects/tejara/screenshot3.png',
      'assets/projects/tejara/screenshot4.png',
      'assets/projects/tejara/screenshot5.png',
      'assets/projects/tejara/screenshot6.png',
      'assets/projects/tejara/screenshot7.png',
      'assets/projects/tejara/screenshot8.png',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Provider',
      'Shared Preferences',
    ],
  ),
  Project(
    slug: 'wardi',
    title: 'Wardi Store',
    kind: ProjectKind.mobile,
    category: 'E-Commerce',
    tagline: 'An e-commerce store app',
    year: '2021',
    description: 'The Wardi Store e-commerce shopping app.',
    platforms: [
      'iOS',
    ],
    appStore: 'https://apps.apple.com/eg/app/id1560876131',
    image: 'assets/projects/wardi/logo.webp',
    screenshots: [
      'assets/projects/wardi/screenshot1.webp',
      'assets/projects/wardi/screenshot2.webp',
    ],
    skills: [
      'Flutter',
      'Dart',
      'Restful API',
      'Provider',
      'Shared Preferences',
    ],
  ),
];
