import 'constants.dart';

const myProjects = [
  {
    'title': 'Omni Lab',
    'description':
        'Omni labs is an application to help dentists to order dental lab services in easier and faster way , same time to follow the progress of their orders step by step',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.omnilabs.omni_labs',
    'app_store': 'https://apps.apple.com/app/omni-lab/id1671362785',
    'web': null,
    'image': '$projectBaseURL/projects_images/Omni%20Labs/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot1.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot2.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot3.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot4.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot5.png',
      '$projectBaseURL/projects_images/Omni%20Labs/screenshot6.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'NodeJS',
      'mongoDB',
      'RestfulAPI',
      'Firebase',
      'SocketIO',
      'Responsive',
      'Express',
      'Git',
      'GitHub',
    ],
  },
  {
    'title': 'تقويم السعودية',
    'description':
        'تطبيق تقويم السعودية المجاني للتذكير بجميع المناسبات في السعودية بالتاريخ الهجري والميلادي، على سبيل المثال:\n- موعد الرواتب للموظفين والمتقاعدين.\n- موعد حساب المواطن.\n- موعد الضمان الاجتماعي.\n- التقويم الدراسي.\n- المناسبات العامة.\n- الندوات والمؤتمرات.\n- المعارض والمهرجانات.\n- مناسباتك الخاصة ويمكن استرجاع جميع المناسبات بعد حذف التطبيق أو مزامنتها مع جهاز آخر.\n- تاريخ اليوم.\n- التحكم بجميع الاعدادات.\n- الوضع الداكن.\nوغيرها من المميزات في التطبيق',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.saudicalendars.app',
    'app_store':
        'https://apps.apple.com/us/app/%D8%AA%D9%82%D9%88%D9%8A%D9%85-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9/id1479182106',
    'web': null,
    'image': '$projectBaseURL/projects_images/Saudi%20Calendars/icon.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot1.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot2.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot3.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot4.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot5.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot6.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot7.png',
      '$projectBaseURL/projects_images/Saudi%20Calendars/screenshot8.png'
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'التقويم الدراسي السعودي',
    'description':
        'تطبيق التقويم الدراسي\nحسب وزارة التعليم في المملكة العربية السعودية\nعداد تنازلي لتاريخ الإجازات والاختبارات\nودجت لمتابعة أقرب موعد مباشرة\nمتابعة موعد الرواتب\nمتابعة مناسبات عامة\nإضافة قسم للمناسبات الخاصة لمستخدم التطبيق',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.saudicalendars.academic',
    'app_store':
        'https://apps.apple.com/us/app/%D8%A7%D9%84%D8%AA%D9%82%D9%88%D9%8A%D9%85-%D8%A7%D9%84%D8%AF%D8%B1%D8%A7%D8%B3%D9%8A-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A/id1319273089',
    'web': null,
    'image': '$projectBaseURL/projects_images/Academic%20Calendar/icon.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot1.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot2.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot3.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot4.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot5.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot6.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot7.png',
      '$projectBaseURL/projects_images/Academic%20Calendar/screenshot8.png'
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'أوقات الصلاة',
    'description':
        'Prayer times app is free and without ads.\nAlerts you to prayer times in all cities of the world.\nDisplay prayer times for the current day, upcoming days, and previous days.\nDirection of the qiblah.\nShow upcoming Islamic events.\nControl the alarm settings for each prayer.\nControl the choice of the muezzin, geographical location, and language.',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.prayer_times.app',
    'app_store': 'https://apps.apple.com/sa/app/prayer-times-app/id1557466684',
    'web': null,
    'image': '$projectBaseURL/projects_images/Prayer%20Times/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot1.jpeg',
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot2.jpeg',
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot3.jpeg',
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot4.jpeg',
      '$projectBaseURL/projects_images/Prayer%20Times/screenshot5.jpeg'
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'فعاليات السعودية',
    'description':
        'فعاليات السعودية يهتم بعرض أحدث الفعاليات والمهرجانات والمناسبات في السعودية مع إمكانية حفظها ومشاركتها والتذكير بها، علي سبيل المثال:\n- المناسبات العامة.\n- الندوات والمؤتمرات.\n- المعارض والمهرجانات.\n- المواسم والفعاليات.\n- موعد الرواتب للموظفين والمتقاعدين.\n- التقويم الدراسي.\n- مناسباتك الخاصة ويمكن استرجاع جميع المناسبات بعد حذف التطبيق أو مزامنتها مع جهاز آخر.\n- تاريخ اليوم.\n- التحكم بجميع الاعدادات.\n- الوضع الداكن.\nوغيرها من المميزات في التطبيق.',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.ksaevent.app',
    'app_store':
        'https://apps.apple.com/us/app/%D9%81%D8%B9%D8%A7%D9%84%D9%8A%D8%A7%D8%AA-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9/id6444774683',
    'web': null,
    'image': '$projectBaseURL/projects_images/KSA%20Events/logo.jpeg',
    'screenshots': [
      '$projectBaseURL/projects_images/KSA%20Events/screenshot1.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot2.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot3.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot4.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot5.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot6.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot7.png',
      '$projectBaseURL/projects_images/KSA%20Events/screenshot8.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'دليل نت',
    'description':
        'دليل لعرض أفضل التطبيقات والمواقع وحسابات شبكات التواصل الاجتماعي\nقم ببناء مفضلتك الخاصة بسرعة\nأضف مواقعك وتطبيقاتك وحساباتك المفضلة\nمفكرة لحفظ ملاحظاتك ومهامك\nمدونة لعرض جديد الأخبار والمعلومات\nوالمزيد ..',
    'google_play':
        'https://play.google.com/store/apps/details?id=net.dleel.dleel',
    'app_store':
        'https://apps.apple.com/us/app/%D8%AF%D9%84%D9%8A%D9%84-%D9%86%D8%AA/id1588625301',
    'web': null,
    'image': '$projectBaseURL/projects_images/Dleel/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Dleel/screenshot1.png',
      '$projectBaseURL/projects_images/Dleel/screenshot2.png',
      '$projectBaseURL/projects_images/Dleel/screenshot3.png',
      '$projectBaseURL/projects_images/Dleel/screenshot4.png',
      '$projectBaseURL/projects_images/Dleel/screenshot5.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Home Widget',
      'Hive',
      'RiverPod',
    ],
  },
  {
    'title': 'Hayat Almuslim',
    'description':
        'For All Muslims This App Contains Quran, Hadith, Tafseer, Learning Quran, Azkar, Sebha And More Uploaded On Google Play',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.quran_and_azkar.quran_and_azkar_app',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Hayat%20Almuslim/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot1.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot2.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot3.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot4.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot5.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot6.png',
      '$projectBaseURL/projects_images/Hayat%20Almuslim/screenshot7.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Hive',
      'GetX',
    ],
  },
  {
    'title': 'Bank El-Dam App',
    'description':
        'This App For Collect Blood From All Users To Hospitals And Others Need This Blood Uploaded On Google Play And App Store',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.bankeldam.egypt',
    'app_store':
        'https://apps.apple.com/eg/app/%D8%A8%D9%86%D9%83-%D8%A7%D9%84%D8%AF%D9%85/id1547670843?l=ar',
    'web': null,
    'image': '$projectBaseURL/projects_images/Bank%20Aldam/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Bank%20Aldam/screenshot1.png',
      '$projectBaseURL/projects_images/Bank%20Aldam/screenshot2.png',
      '$projectBaseURL/projects_images/Bank%20Aldam/screenshot3.png',
      '$projectBaseURL/projects_images/Bank%20Aldam/screenshot4.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Hive',
      'GetX',
    ],
  },
  {
    'title': 'Tejara E-Commerece',
    'description':
        'This App For E-Commerce Uploaded On Google Play And App Store',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.tejaraqa.tejara',
    'app_store': 'https://apps.apple.com/us/app/tejara/id1540453728',
    'web': null,
    'image': '$projectBaseURL/projects_images/Tejara/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Tejara/screenshot1.png',
      '$projectBaseURL/projects_images/Tejara/screenshot2.png',
      '$projectBaseURL/projects_images/Tejara/screenshot3.png',
      '$projectBaseURL/projects_images/Tejara/screenshot4.png',
      '$projectBaseURL/projects_images/Tejara/screenshot5.png',
      '$projectBaseURL/projects_images/Tejara/screenshot6.png',
      '$projectBaseURL/projects_images/Tejara/screenshot7.png',
      '$projectBaseURL/projects_images/Tejara/screenshot8.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Git',
      'GitHub',
      'Shared Preference',
      'Provider',
    ],
  },
  {
    'title': 'Wardi E-Commerece',
    'description':
        'This App For E-Commerce Uploaded On Google Play And App Store',
    'google_play': null,
    'app_store':
        'https://apps.apple.com/eg/app/%D9%85%D8%AA%D8%AC%D8%B1-%D9%88%D8%B1%D8%AF%D9%8A-wardi-store/id1560876131?l=ar',
    'web': null,
    'image': '$projectBaseURL/projects_images/Wardi/logo.webp',
    'screenshots': [
      '$projectBaseURL/projects_images/Wardi/screenshot1.webp',
      '$projectBaseURL/projects_images/Wardi/screenshot2.webp'
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Git',
      'GitHub',
      'Shared Preference',
      'Provider',
    ],
  },
  {
    'title': 'Afaky ERP',
    'description':
        'This App Is ERP System Mobile Version App And Also Work On Web , It Uploaded On Google Play And App Store',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.afakyerp.afaky',
    'app_store': 'https://apps.apple.com/us/app/afaky-app/id1622146478',
    'web': null,
    'image': '$projectBaseURL/projects_images/Afaky/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Afaky/screenshot1.png',
      '$projectBaseURL/projects_images/Afaky/screenshot2.png',
      '$projectBaseURL/projects_images/Afaky/screenshot3.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Shared Preferences',
      'Bloc',
    ],
  },
  {
    'title': 'Gala Order',
    'description':
        'This App For Food Ordering That You Can Order Food From Any Restaruant And Delivery Will Deliver It To You And It Has Delivery App And Two Control Panels For Admin And Restaurant And It Uploaded On Google Play And App Store',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.user.gala',
    'app_store': 'https://apps.apple.com/us/app/gala-order/id1640057386',
    'web': null,
    'image': '$projectBaseURL/projects_images/Gala%20Order/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Gala%20Order/screenshot1.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot2.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot3.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot4.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot5.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot6.png',
      '$projectBaseURL/projects_images/Gala%20Order/screenshot7.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Shared Preferences',
      'GetX',
    ],
  },
  {
    'title': 'Gala Driver',
    'description': 'This App For The Delivery Of Gala Order App',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.gala.gala_rider',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Gala%20Driver/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot1.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot2.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot3.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot4.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot5.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot6.jpeg',
      '$projectBaseURL/projects_images/Gala%20Driver/screenshot7.jpeg',
    ],
    'skills': [
      'Flutter',
      'dart',
      'RestfulAPI',
      'Firebase',
      'Git',
      'GitHub',
      'Shared Preferences',
      'GetX',
    ],
  },
  {
    'title': 'QR Generator & Scanner',
    'description':
        'This App For Generate And Scan QR Code And Extrac All Data You Generated It Uploaded On Google Play',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.mohamednagdy.qrscannerandreader',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/QR%20Scanner/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/QR%20Scanner/screenshot1.png',
      '$projectBaseURL/projects_images/QR%20Scanner/screenshot2.png',
      '$projectBaseURL/projects_images/QR%20Scanner/screenshot3.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'QR Code',
      'Git',
      'GitHub',
      'Local Storage',
      'GetX',
    ],
  },
  {
    'title': 'أكاديمية علمني',
    'description':
        'This App Is Webview Based App For Allemny Academy Uploaded On Google Play',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.u3allemny.allemny',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Allemny/logo.jpeg',
    'screenshots': [
      '$projectBaseURL/projects_images/Allemny/screenshot1.png',
      '$projectBaseURL/projects_images/Allemny/screenshot2.png',
      '$projectBaseURL/projects_images/Allemny/screenshot3.png',
      '$projectBaseURL/projects_images/Allemny/screenshot4.png',
      '$projectBaseURL/projects_images/Allemny/screenshot5.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Webview',
      'Git',
      'GitHub',
      'GetX',
    ],
  },
  {
    'title': 'ستوريات 2022',
    'description': 'Download All Text And Video Stories From One App',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.storiesstore.store',
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/Whatsapp%20Stories/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot1.png',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot2.jpeg',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot2.png',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot3.jpeg',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot4.jpeg',
      '$projectBaseURL/projects_images/Whatsapp%20Stories/screenshot5.jpeg',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Local Storage',
      'Git',
      'GitHub',
      'GetX',
      'NodeJS',
      'Admin Dashboard',
      'Restful API'
    ],
  },
  {
    'title': 'Helpers',
    'description':
        'small social media network for sharing and posting and creating stories',
    'google_play': null,
    'app_store': 'https://apps.apple.com/us/app/helpers/id6444851510',
    'web': null,
    'image': '$projectBaseURL/projects_images/Helpers/logo.webp',
    'screenshots': [
      '$projectBaseURL/projects_images/Helpers/screenshot1.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot2.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot3.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot4.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot5.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot6.webp',
      '$projectBaseURL/projects_images/Helpers/screenshot7.webp',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Local Storage',
      'Git',
      'GitHub',
      'GetX',
      'NodeJS',
      'Restful API'
    ],
  },
  {
    'title': 'Driving School Dashboard',
    'description':
        'Dashboard for controlling the driving school with all functionality needed for',
    'google_play': null,
    'app_store': null,
    'web': null,
    'image': '$projectBaseURL/projects_images/blue_house_dashboard/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot1.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot2.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot3.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot4.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot5.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot6.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot7.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot8.png',
      '$projectBaseURL/projects_images/blue_house_dashboard/screenshot9.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Flutter Web',
      'Git',
      'GitHub',
      'RiverPod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design'
    ],
  },
  {
    'title': 'Blue House Dashboard',
    'description':
        'Dashboard for controlling Blue House App And Show All Orders And all payments',
    'google_play': null,
    'app_store': null,
    'web': null,
    'image':
        '$projectBaseURL/projects_images/driving_school_dashboard/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot1.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot2.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot3.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot4.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot5.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot6.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot7.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot8.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot9.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot10.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot11.png',
      '$projectBaseURL/projects_images/driving_school_dashboard/screenshot12.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Flutter Web',
      'Git',
      'GitHub',
      'RiverPod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design'
    ],
  },
  {
    'title': 'Blue House - User',
    'description': 'Show and order gates from every where in qatar',
    'google_play':
        'https://play.google.com/store/apps/details?id=com.pipeline.bluehousecustomerapp_v1',
    'app_store': 'https://apps.apple.com/us/app/blue-house-qatar/id6448504307',
    'web': null,
    'image': '$projectBaseURL/projects_images/Blue%20House%20-%20User/logo.png',
    'screenshots': [
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot1.png',
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot2.png',
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot3.png',
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot4.png',
      '$projectBaseURL/projects_images/Blue%20House%20-%20User/screenshot5.png',
    ],
    'skills': [
      'Flutter',
      'dart',
      'Git',
      'GitHub',
      'RiverPod',
      'NodeJS',
      'mongoDB',
      'Restful API',
      'Responsive Design'
    ],
  }
];
